-- CREATE TABLE itsme (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   question TEXT NOT NULL,
--   answer_ko TEXT NOT NULL,
--   answer_ja TEXT,
--   tags TEXT[],
--   image_paths TEXT[],
--   -- 타입을 vector가 아닌 halfvec으로 지정합니다.
--   embedding halfvec(3072),
--   created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
-- );

-- -- 2. halfvec 타입에 HNSW 인덱스 생성
-- -- halfvec은 2000차원 제한을 받지 않습니다.
-- CREATE INDEX ON itsme USING hnsw (embedding halfvec_cosine_ops);

-- -- (선택) 태그 검색을 위한 인덱스
-- CREATE INDEX ON itsme USING GIN (tags);

-- 기존 테이블 삭제
DROP TABLE IF EXISTS itsme;

-- 새로운 구조로 테이블 생성 (metadata 추가)
CREATE TABLE itsme (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  answer_ko TEXT NOT NULL,
  answer_ja TEXT,
  tags TEXT[],
  image_paths TEXT[],
  metadata JSONB DEFAULT '{}',  -- 새로 추가된 컬럼
  embedding halfvec(3072),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- halfvec HNSW 인덱스 (기존과 동일)
CREATE INDEX ON itsme USING hnsw (embedding halfvec_cosine_ops);

-- 태그 검색 인덱스 (기존과 동일)
CREATE INDEX ON itsme USING GIN (tags);

-- JSONB 검색을 위한 GIN 인덱스 (새로 추가)
CREATE INDEX ON itsme USING GIN (metadata);